/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      colors: {
        primary: {
          DEFAULT: "#8C74FF",
          50: "#F5F2FF",
          100: "#E6E0FF",
          200: "#C9BEFF",
          300: "#AD9CFF",
          400: "#907AFF",
          500: "#8C74FF",
          600: "#7057CC",
          700: "#543A99",
          800: "#381D66",
          900: "#1C0033",
        },
        gray: {
          DEFAULT: "#898989",
          50: "#F7F7F7",
          100: "#EBEBEB",
          200: "#D6D6D6",
          300: "#C2C2C2",
          400: "#ADADAD",
          500: "#898989",
          600: "#727272",
          700: "#5C5C5C",
          800: "#454545",
          900: "#2E2E2E",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "3.75rem",
        "7xl": "4.5rem",
        hero: "100px",
        "section-title": "50px",
        "sub-hero": "32px",
        "nav-link": "14px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      maxWidth: {
        "nav-container": "857px",
        "hero-image": "1253px",
        "feature-box": "299px",
        "big-message": "1253px",
        "pricing-tier": "392px",
        "input-box": "449px",
        "footer": "1362px",
      },
      width: {
        "nav-container": "857px",
        "nav-button": "107px",
        "hero-image": "1253px",
        "feature-box": "299px",
        "big-message": "1253px",
        "pricing-tier": "392px",
        "input-box": "449px",
        "footer": "1362px",
      },
      height: {
        "nav-container": "67px",
        "nav-button": "41px",
        "hero-image": "685px",
        "feature-box": "351px",
        "ai-feature-box": "228px",
        "big-message": "293px",
        "pricing-tier": "496px",
        "input-box": "53px",
        "footer": "450px",
      },
    },
  },
  plugins: [import("tailwindcss-animate")],
}

